#check https://realm.github.io/SwiftLint/rule-directory.html

excluded:
  - build
  - build/*
  - DerivedData
  - DerivedData/*

type_name:
  excluded:
    - DeviceSizeCategoryProvider.swift
    - GeneratedAssetSymbols.swift

