package de.stefan.lang.di

import java.io.File
import org.gradle.api.DefaultTask
import org.gradle.api.artifacts.ProjectDependency
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

abstract class GenerateDiDependenciesTask : DefaultTask() {

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val className: Property<String>

    @get:Input
    abstract val moduleClasses: ListProperty<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val modules = moduleClasses.get()
        val outputDirectory = outputDir.get().asFile
        if (!outputDirectory.exists()) {
            outputDirectory.mkdirs()
        }
        val outputFile = File(outputDirectory, "${className.get()}.kt")
        outputFile.writeText(renderFile(modules))
    }

    private fun renderFile(modules: List<String>): String {
        val pkg = packageName.get()
        val klass = className.get()
        val imports = modules.toSet().sorted()
        val modulesList = modules.joinToString(separator = ",\n") {
            "        ${simpleName(it)}"
        }
        return buildString {
            appendLine("// Generated by GenerateDiDependenciesTask. Do not modify manually.")
            appendLine("package $pkg")
            appendLine()
            appendLine("import de.stefan.lang.core.di.RootModule")
            imports.forEach { appendLine("import $it") }
            appendLine()
            appendLine("internal object $klass {")
            appendLine("    val modules: List<RootModule> = listOf(")
            if (modules.isNotEmpty()) {
                appendLine(modulesList)
            }
            appendLine("    )")
            appendLine("}")
        }
    }

    private fun simpleName(fqcn: String): String = fqcn.substringAfterLast('.')
}
